# Wdróż w Static Web Apps

# Na podstawie:
# https://stackoverflow.com/questions/67642978/create-react-app-hosted-as-static-app-on-azure-doesnt-detect-env-vars
# https://gist.github.com/bhagavan44/ed11fb5199667fd0d4aeddf346a3a870

trigger:
    branches:
        include:
            - master

pool:
    vmImage: ubuntu-latest

steps:
    - checkout: self
      displayName: Checkout code

    - script: yarn install
      displayName: yarn install

    - script: yarn build
      displayName: yarn build

    - task: AzureStaticWebApp@0
      displayName: Deploy
      inputs:
          skip_app_build: true
          app_location: 'ui/public'
          config_file_location: '/'
          azure_static_web_apps_api_token: '$(deployment_token)'
