name: Lint & test

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - 'synchronize'
            - 'opened'
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
    # Akcja przygotowująca zależności, generująca w ten sposób cache dla pozostałych operacji
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - run: yarn --frozen-lockfile

    lint:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - run: yarn --frozen-lockfile
            - run: yarn lint

    test:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - run: yarn --frozen-lockfile
            - run: yarn test

    svelte-check:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - run: yarn --frozen-lockfile
            - run: yarn build:core
            - run: yarn ui run check
