name: Run lint

on:
    push:
        branches: ['main']

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - run: yarn lint
